apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xzct2yj9i-java-quarkus-stage
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/xzct2yj9i-java-quarkus/overlays/stage
    repoURL: https://github.com/rhtap-rhdh-qe/xzct2yj9i-java-quarkus-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-stage
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

